DEF_ERROR(ERROR_NONE,                       "no error, all success")
DEF_ERROR(ERROR_NUMBER_FORMAT,              "invalid number format")
DEF_ERROR(ERROR_UNTERMINATED_STRING,        "unterminated string")
DEF_ERROR(ERROR_INVALID_OPERATOR,           "invalid operator")
DEF_ERROR(ERROR_NOT_UNARY,					"operator is not unary")
DEF_ERROR(ERROR_MISSING_BRACKET,			"bracket is missing")
DEF_ERROR(ERROR_NOT_A_NUMBER,               "token is not a number")
DEF_ERROR(ERROR_EOF,                        "parsing is not done")
