DEF_ERROR(ERROR_NONE,                       "No error, all success")
DEF_ERROR(ERROR_NUMBER_FORMAT,              "Invalid number format")
DEF_ERROR(ERROR_UNTERMINATED_STRING,        "Unterminated string")
DEF_ERROR(ERROR_INVALID_OPERATOR,           "Invalid operator")
DEF_ERROR(ERROR_NOT_UNARY,					"Operator is not unary")
DEF_ERROR(ERROR_MISSING_BRACKET,			"Bracket is missing")
